In [2]:
import numpy as np

In [7]:
arr1=np.array([10,20,30,40,50,60,70])

In [8]:
# append()
# Adding elements at the end
print(np.append(arr1,80))
print(np.append(arr1,90))
print(np.append(arr1,100))
print(np.append(arr1,120))

[10 20 30 40 50 60 70 80]
[10 20 30 40 50 60 70 90]
[ 10  20  30  40  50  60  70 100]
[ 10  20  30  40  50  60  70 120]


In [10]:
arr2=np.array([[2,3,4],[7,8,9]])
# for 2D array
print(np.append(arr2,10))
print(np.append(arr2,90))
print(np.append(arr2,60))

[ 2  3  4  7  8  9 10]
[ 2  3  4  7  8  9 90]
[ 2  3  4  7  8  9 60]


In [5]:
# insert() method 
arr1=np.array([10,20,30,40,50,60,70])
print(np.insert(arr1,1,80)) # 80 will add at index 1
print(np.insert(arr1,5,210)) # 210 will add at index 5

[10 80 20 30 40 50 60 70]
[ 10  20  30  40  50 210  60  70]


In [7]:
arr2=np.array([[2,3,4],[7,8,9]]) #for 2D array
print(np.insert(arr2,4,100)) # 100 will add at the index 4
print(np.insert(arr2,1,210)) # 210 will add at the index 1

[  2   3   4   7 100   8   9]
[  2 210   3   4   7   8   9]


In [17]:
# delete() method
# to remove elements for array
arr1=np.array([10,20,30,40,50,60,70])
print(np.delete(arr1,3)) #value at index 3 will delete
print(np.delete(arr1,[1,2,3]))

[10 20 30 50 60 70]
[10 50 60 70]
