In [1]:
import numpy as np
# to perform scientific and mathematical calculations

In [3]:
# Array
# Collection of items that are stored at contiguous memory
# Same datatype
arr1=np.array([2,4,6,3,8,9]) #array creation
print(arr1)
print(type(arr1))


[2 4 6 3 8 9]
<class 'numpy.ndarray'>


In [9]:
# Array Slicing
print(arr1[0:4])
print(arr1[3:5])
print(arr1[:3])
print(arr1[3:])
print(arr1[:])

[2 4 6 3]
[3 8]
[2 4 6]
[3 8 9]
[2 4 6 3 8 9]


In [21]:
arr2=np.array([[10,20,30,40],[50,60,70,80]]) #2D array
# Array Slicing
print(arr2[0:3,0:3])
print(arr2[0,0:2])
print(arr2[1,0:3])
print(arr2[1,1:3])
print(arr2[0,2])
print(arr2[1,1])

[[10 20 30]
 [50 60 70]]
[10 20]
[50 60 70]
[60 70]
30
60


In [28]:
arr3=np.array([10,20,30,40,50,60,70,80])
arr4=np.array([[3,6,9],[2,4,6]])
# Attributes of an array
print(np.shape(arr3)) #gives count of rows and columns
print(np.size(arr3)) #gives total number of elements present in the array
print(np.size(arr4))
print(len(arr3)) #gives length of an array
print(len(arr4))
print(np.ndim(arr3)) #gives how many dimentions array holds 
print(np.ndim(arr4))
print(arr3.astype(str)) #convert to string datatype
print(arr3.astype(float)) #convert to float datatype

(8,)
8
6
8
2
1
2
['10' '20' '30' '40' '50' '60' '70' '80']
[10. 20. 30. 40. 50. 60. 70. 80.]
[10 20 30 40 50 60 70 80]
