In [2]:
import numpy as np

In [3]:
arr1=np.array([30,40,50])
arr2=np.array([5,5,3])
# concatenation
#to add two array we use concatenate
print(np.concatenate([arr1,arr2]))

[30 40 50  5  5  3]


In [9]:
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([[1,2,3],[4,5,6]])
# we can add two 2D array by two diiferent way axis=0 and axis=1
# axis=0 means adding vertically
# we can also use vstack to add two 2D array
# default value for concatenate is axis=0
print(np.concatenate([arr1,arr2])) #default

[[10 20 30]
 [40 50 60]
 [ 1  2  3]
 [ 4  5  6]]


In [11]:
# using axis=0
print(np.concatenate([arr1,arr2],axis=0))

[[10 20 30]
 [40 50 60]
 [ 1  2  3]
 [ 4  5  6]]


In [12]:
# using vstack method
print(np.vstack([arr1,arr2]))

[[10 20 30]
 [40 50 60]
 [ 1  2  3]
 [ 4  5  6]]


In [13]:
# axis=1
# it will add two arrays horizontally
# we can use hstack to add horizontally by axis=1

# using axis=1
print(np.concatenate([arr1,arr2],axis=1))

[[10 20 30  1  2  3]
 [40 50 60  4  5  6]]


In [14]:
# using hstack method
print(np.hstack([arr1,arr2]))

[[10 20 30  1  2  3]
 [40 50 60  4  5  6]]


In [15]:
# splitting of an array
# making different parts of an array from a single array is splitting
# we use array_split method for splitting
arr1=np.array([10,20,30,40,50,60])
print(np.array_split(arr1,3)) #this will split array in three parts  

[array([10, 20]), array([30, 40]), array([50, 60])]


In [17]:
# we can access the splitted array throught indexing
splitted=np.array_split(arr1,3)
print(splitted[0])
print(splitted[1])
print(splitted[2])

[10 20]
[30 40]
[50 60]


In [19]:
# for 2D array
# we cannot split 2D array into multiple parts it can only split into two parts
# if we did multiple parts the other parts were empty
arr2=np.array([[10,20,30],[40,50,60]])
print(np.array_split(arr2,2))
pr

[array([[10, 20, 30]]), array([[40, 50, 60]]), array([], shape=(0, 3), dtype=int64)]
