In [1]:
import numpy as np

In [2]:
arr1=np.array([2,4,6,8,10,12])
arr2=np.array([1,3,5,7,9,11])
# Sum of two arrays

[ 2  4  6  8 10 12]
[ 1  3  5  7  9 11]


In [3]:
# Sum of two arrays
print(np.add(arr1,arr2))

[ 3  7 11 15 19 23]


In [5]:
# Substraction of two arrays
print(np.subtract(arr1,arr2))

[1 1 1 1 1 1]


In [6]:
# division of two arrays
print(np.divide(arr1,arr2))

[2.         1.33333333 1.2        1.14285714 1.11111111 1.09090909]


In [7]:
# Multiplication of two arrays
print(np.multiply(arr1,arr2))

[  2  12  30  56  90 132]


In [8]:
# Power of array
arr3=np.array([1,2,3,4,5,6,7,8,9])
arr4=np.array([2])
print(np.power(arr3,arr4))

[ 1  4  9 16 25 36 49 64 81]


In [9]:
# Square Root of array
arr5=np.array([1,4,9,16,25,36,49,64,81])
print(np.sqrt(arr5))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
