Sorting And Searching

In [1]:
import numpy as np

In [2]:
# sorting
# to arrange the numbers in ascending order
# we use direct sort() method to sort the data
arr1=np.array([3,23,5,8,67,1,36,89,24])
print(np.sort(arr1))

[ 1  3  5  8 23 24 36 67 89]


In [3]:
arr2=np.array([-12,23,4,1,3,76,34,4,45])
print(np.sort(arr2))

[-12   1   3   4   4  23  34  45  76]


In [4]:
# For 2D array
arr1=np.array([[3,45,2,76,12,34,7,23],[34,45,2,56,4,23,45,76]])
print(np.sort(arr1))
# This how sorting works in 2D array it will sort each array one by one

[[ 2  3  7 12 23 34 45 76]
 [ 2  4 23 34 45 45 56 76]]


In [5]:
# Searching
arr = np.array([10, 20, 30, 40, 50])

# To find the index where value is 30
result = np.where(arr == 30)

print("Index where value is 30:", result)

Index where value is 30: (array([2]),)


In [6]:
arr = np.array([5, 12, 7, 25, 10, 50])

# To find indexes where value > 10
result = np.where(arr > 10)

print("Indexes where value is greater than 10:", result)

Indexes where value is greater than 10: (array([1, 3, 5]),)
